; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Thu Jun 11 2020 20:53:45 GMT+0200 (heure d’été d’Europe centrale)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


