; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2 on Mon Apr 08 2019 13:38:58 GMT+0200 (heure d’été d’Europe centrale)

