; generated by PrusaSlicer 2.1.0+win64 on 2019-10-19 at 18:39:22 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.60mm

M107 ; disable fan
M190 S110 ; set bed temperature and wait for it to be reached
M104 S240 ; set temperature
;M42 P2 S64   ; LED at 30% PWM on heater 2
;G32               ; bed levelling
G28 Z0          ; home all axes
G29 S1         ; load heightmap
G1 Z5 F5000 ; lift nozzle
M109 S240 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0 ; reset extrusion distance
; Filament gcode
G10 ; retract
G92 E0 ; reset extrusion distance
G1 Z0.300 F7800.000 ; move to next layer (0)
G1 X107.074 Y107.559 ; move to first skirt point
G11 ; unretract
G92 E0 ; reset extrusion distance
G1 F1800
G1 X108.167 Y106.576 E0.10166 ; skirt
G1 X109.435 Y105.832 E0.20331 ; skirt
G1 X110.825 Y105.355 E0.30497 ; skirt
G1 X112.283 Y105.164 E0.40663 ; skirt
G1 X187.507 Y105.161 E5.60882 ; skirt
G1 X188.877 Y105.291 E5.70403 ; skirt
G1 X190.205 Y105.678 E5.79970 ; skirt
G1 X191.432 Y106.303 E5.89491 ; skirt
G1 X192.525 Y107.151 E5.99057 ; skirt
G1 X193.439 Y108.189 E6.08624 ; skirt
G1 X194.140 Y109.374 E6.18145 ; skirt
G1 X194.609 Y110.676 E6.27712 ; skirt
G1 X194.825 Y112.042 E6.37278 ; skirt
G1 X194.837 Y187.674 E11.60320 ; skirt
G1 X194.689 Y188.976 E11.69379 ; skirt
G1 X194.312 Y190.230 E11.78439 ; skirt
G1 X193.718 Y191.398 E11.87499 ; skirt
G1 X192.926 Y192.441 E11.96559 ; skirt
G1 X191.795 Y193.451 E12.07047 ; skirt
G1 X190.486 Y194.204 E12.17489 ; skirt
G1 X189.044 Y194.675 E12.27977 ; skirt
G1 X187.543 Y194.839 E12.38419 ; skirt
G1 X112.326 Y194.837 E17.58592 ; skirt
G1 X111.024 Y194.689 E17.67652 ; skirt
G1 X109.770 Y194.312 E17.76712 ; skirt
G1 X108.602 Y193.718 E17.85772 ; skirt
G1 X107.559 Y192.926 E17.94831 ; skirt
G1 X106.549 Y191.795 E18.05319 ; skirt
G1 X105.796 Y190.486 E18.15761 ; skirt
G1 X105.325 Y189.044 E18.26249 ; skirt
G1 X105.161 Y187.543 E18.36691 ; skirt
G1 X105.163 Y112.326 E23.56865 ; skirt
G1 X105.311 Y111.024 E23.65925 ; skirt
G1 X105.688 Y109.770 E23.74984 ; skirt
G1 X106.282 Y108.602 E23.84044 ; skirt
G1 X107.038 Y107.606 E23.92689 ; skirt
G1 X107.463 Y107.932 F7800.000 ; move to first skirt point
G1 F1800
G1 X108.501 Y106.996 E24.02351 ; skirt
G1 X109.673 Y106.312 E24.11738 ; skirt
G1 X110.964 Y105.872 E24.21170 ; skirt
G1 X112.310 Y105.699 E24.30557 ; skirt
G1 X187.506 Y105.697 E29.50584 ; skirt
G1 X188.781 Y105.818 E29.59439 ; skirt
G1 X190.016 Y106.179 E29.68338 ; skirt
G1 X191.156 Y106.762 E29.77194 ; skirt
G1 X192.171 Y107.554 E29.86093 ; skirt
G1 X193.019 Y108.522 E29.94993 ; skirt
G1 X193.667 Y109.626 E30.03848 ; skirt
G1 X194.096 Y110.833 E30.12703 ; skirt
G1 X194.292 Y112.104 E30.21602 ; skirt
G1 X194.302 Y187.655 E35.44078 ; skirt
G1 X194.164 Y188.870 E35.52534 ; skirt
G1 X193.811 Y190.040 E35.60990 ; skirt
G1 X193.255 Y191.129 E35.69446 ; skirt
G1 X192.512 Y192.100 E35.77901 ; skirt
G1 X191.468 Y193.027 E35.87555 ; skirt
G1 X190.251 Y193.723 E35.97252 ; skirt
G1 X188.923 Y194.153 E36.06906 ; skirt
G1 X187.535 Y194.303 E36.16559 ; skirt
G1 X112.345 Y194.302 E41.36541 ; skirt
G1 X111.130 Y194.164 E41.44997 ; skirt
G1 X109.960 Y193.811 E41.53453 ; skirt
G1 X108.871 Y193.255 E41.61909 ; skirt
G1 X107.900 Y192.512 E41.70364 ; skirt
G1 X106.973 Y191.468 E41.80018 ; skirt
G1 X106.277 Y190.251 E41.89715 ; skirt
G1 X105.847 Y188.923 E41.99369 ; skirt
G1 X105.697 Y187.535 E42.09022 ; skirt
G1 X105.698 Y112.345 E47.29004 ; skirt
G1 X105.836 Y111.130 E47.37460 ; skirt
G1 X106.189 Y109.960 E47.45916 ; skirt
G1 X106.745 Y108.871 E47.54372 ; skirt
G1 X107.427 Y107.979 E47.62133 ; skirt
G1 X107.851 Y108.305 F7800.000 ; move to first skirt point
G1 F1800
G1 X108.831 Y107.419 E47.71267 ; skirt
G1 X109.915 Y106.790 E47.79936 ; skirt
G1 X111.103 Y106.390 E47.88604 ; skirt
G1 X112.340 Y106.234 E47.97230 ; skirt
G1 X187.506 Y106.232 E53.17048 ; skirt
G1 X188.687 Y106.346 E53.25248 ; skirt
G1 X189.824 Y106.679 E53.33448 ; skirt
G1 X190.879 Y107.221 E53.41649 ; skirt
G1 X191.813 Y107.952 E53.49849 ; skirt
G1 X192.592 Y108.846 E53.58049 ; skirt
G1 X193.189 Y109.870 E53.66250 ; skirt
G1 X193.583 Y110.989 E53.74450 ; skirt
G1 X193.759 Y112.161 E53.82650 ; skirt
G1 X193.766 Y187.630 E59.04562 ; skirt
G1 X193.640 Y188.759 E59.12422 ; skirt
G1 X193.314 Y189.842 E59.20239 ; skirt
G1 X192.799 Y190.848 E59.28056 ; skirt
G1 X192.107 Y191.750 E59.35915 ; skirt
G1 X191.144 Y192.599 E59.44797 ; skirt
G1 X190.029 Y193.235 E59.53678 ; skirt
G1 X188.807 Y193.630 E59.62560 ; skirt
G1 X187.530 Y193.768 E59.71441 ; skirt
G1 X112.370 Y193.766 E64.91215 ; skirt
G1 X111.241 Y193.640 E64.99075 ; skirt
G1 X110.158 Y193.314 E65.06892 ; skirt
G1 X109.152 Y192.799 E65.14709 ; skirt
G1 X108.250 Y192.107 E65.22569 ; skirt
G1 X107.401 Y191.144 E65.31450 ; skirt
G1 X106.765 Y190.029 E65.40331 ; skirt
G1 X106.370 Y188.807 E65.49213 ; skirt
G1 X106.232 Y187.530 E65.58094 ; skirt
G1 X106.234 Y112.370 E70.77869 ; skirt
G1 X106.360 Y111.241 E70.85728 ; skirt
G1 X106.686 Y110.158 E70.93545 ; skirt
G1 X107.201 Y109.152 E71.01362 ; skirt
G1 X107.815 Y108.352 E71.08333 ; skirt
G10 ; retract
G92 E0 ; reset extrusion distance
G1 X186.129 Y186.129 F7800.000 ; move to first perimeter point
G11 ; unretract
G92 E0 ; reset extrusion distance
G1 F1800
G1 X113.871 Y186.129 E4.99705 ; perimeter
G1 X113.871 Y113.871 E9.99411 ; perimeter
G1 X186.129 Y113.871 E14.99116 ; perimeter
G1 X186.129 Y186.069 E19.98406 ; perimeter
G1 X186.664 Y186.664 F7800.000 ; move to first perimeter point
G1 F1800
G1 X113.336 Y186.664 E25.05520 ; perimeter
G1 X113.336 Y113.336 E30.12633 ; perimeter
G1 X186.664 Y113.336 E35.19747 ; perimeter
G1 X186.664 Y186.604 E40.26445 ; perimeter
G1 X187.200 Y187.200 F7800.000 ; move to first perimeter point
G1 F900
G1 X112.800 Y187.200 E45.40967 ; perimeter
G1 X112.800 Y112.800 E50.55489 ; perimeter
G1 X187.200 Y112.800 E55.70011 ; perimeter
G1 X187.200 Y187.140 E60.84118 ; perimeter
G1 X186.814 Y187.096 F7800.000 ; move inwards before travel
G10 ; retract
G92 E0 ; reset extrusion distance
G1 X185.968 Y115.115 ; move to first infill point
G11 ; unretract
G92 E0 ; reset extrusion distance
G1 F600
G1 X185.126 Y114.273 E0.08240 ; infill
G1 X184.368 Y114.273 E0.13482 ; infill
G1 X185.727 Y115.632 E0.26778 ; infill
G1 X185.727 Y116.390 E0.32021 ; infill
G1 X183.610 Y114.273 E0.52731 ; infill
G1 X182.853 Y114.273 E0.57974 ; infill
G1 X185.727 Y117.147 E0.86098 ; infill
G1 X185.727 Y117.905 E0.91341 ; infill
G1 X182.095 Y114.273 E1.26879 ; infill
G1 X181.337 Y114.273 E1.32122 ; infill
G1 X185.727 Y118.663 E1.75075 ; infill
G1 X185.727 Y119.421 E1.80318 ; infill
G1 X180.579 Y114.273 E2.30685 ; infill
G1 X179.821 Y114.273 E2.35927 ; infill
G1 X185.727 Y120.179 E2.93709 ; infill
G1 X185.727 Y120.936 E2.98952 ; infill
G1 X179.064 Y114.273 E3.64147 ; infill
G1 X178.306 Y114.273 E3.69390 ; infill
G1 X185.727 Y121.694 E4.42000 ; infill
G1 X185.727 Y122.452 E4.47243 ; infill
G1 X177.548 Y114.273 E5.27267 ; infill
G1 X176.790 Y114.273 E5.32509 ; infill
G1 X185.727 Y123.210 E6.19948 ; infill
G1 X185.727 Y123.968 E6.25191 ; infill
G1 X176.032 Y114.273 E7.20043 ; infill
G1 X175.275 Y114.273 E7.25286 ; infill
G1 X185.727 Y124.725 E8.27553 ; infill
G1 X185.727 Y125.483 E8.32796 ; infill
G1 X174.517 Y114.273 E9.42477 ; infill
G1 X173.759 Y114.273 E9.47720 ; infill
G1 X185.727 Y126.241 E10.64815 ; infill
G1 X185.727 Y126.999 E10.70058 ; infill
G1 X173.001 Y114.273 E11.94568 ; infill
G1 X172.244 Y114.273 E11.99810 ; infill
G1 X185.727 Y127.756 E13.31735 ; infill
G1 X185.727 Y128.514 E13.36977 ; infill
G1 X171.486 Y114.273 E14.76316 ; infill
G1 X170.728 Y114.273 E14.81558 ; infill
G1 X185.727 Y129.272 E16.28311 ; infill
G1 X185.727 Y130.030 E16.33554 ; infill
G1 X169.970 Y114.273 E17.87720 ; infill
G1 X169.212 Y114.273 E17.92963 ; infill
G1 X185.727 Y130.788 E19.54544 ; infill
G1 X185.727 Y131.545 E19.59787 ; infill
G1 X168.455 Y114.273 E21.28782 ; infill
G1 X167.697 Y114.273 E21.34025 ; infill
G1 X185.727 Y132.303 E23.10435 ; infill
G1 X185.727 Y133.061 E23.15677 ; infill
G1 X166.939 Y114.273 E24.99501 ; infill
G1 X166.181 Y114.273 E25.04744 ; infill
G1 X185.727 Y133.819 E26.95982 ; infill
G1 X185.727 Y134.577 E27.01225 ; infill
G1 X165.423 Y114.273 E28.99877 ; infill
G1 X164.666 Y114.273 E29.05120 ; infill
G1 X185.727 Y135.334 E31.11187 ; infill
G1 X185.727 Y136.092 E31.16430 ; infill
G1 X163.908 Y114.273 E33.29911 ; infill
G1 X163.150 Y114.273 E33.35153 ; infill
G1 X185.727 Y136.850 E35.56049 ; infill
G1 X185.727 Y137.608 E35.61291 ; infill
G1 X162.392 Y114.273 E37.89601 ; infill
G1 X161.635 Y114.273 E37.94843 ; infill
G1 X185.727 Y138.365 E40.30567 ; infill
G1 X185.727 Y139.123 E40.35810 ; infill
G1 X160.877 Y114.273 E42.78948 ; infill
G1 X160.119 Y114.273 E42.84191 ; infill
G1 X185.727 Y139.881 E45.34743 ; infill
G1 X185.727 Y140.639 E45.39986 ; infill
G1 X159.361 Y114.273 E47.97952 ; infill
G1 X158.603 Y114.273 E48.03195 ; infill
G1 X185.727 Y141.397 E50.68576 ; infill
G1 X185.727 Y142.154 E50.73819 ; infill
G1 X157.846 Y114.273 E53.46614 ; infill
G1 X157.088 Y114.273 E53.51857 ; infill
G1 X185.727 Y142.912 E56.32066 ; infill
G1 X185.727 Y143.670 E56.37309 ; infill
G1 X156.330 Y114.273 E59.24932 ; infill
G1 X155.572 Y114.273 E59.30175 ; infill
G1 X185.727 Y144.428 E62.25213 ; infill
G1 X185.727 Y145.186 E62.30456 ; infill
G1 X154.814 Y114.273 E65.32908 ; infill
G1 X154.057 Y114.273 E65.38151 ; infill
G1 X185.727 Y145.943 E68.48017 ; infill
G1 X185.727 Y146.701 E68.53260 ; infill
G1 X153.299 Y114.273 E71.70541 ; infill
G1 X152.541 Y114.273 E71.75783 ; infill
G1 X185.727 Y147.459 E75.00478 ; infill
G1 X185.727 Y148.217 E75.05721 ; infill
G1 X151.783 Y114.273 E78.37830 ; infill
G1 X151.026 Y114.273 E78.43073 ; infill
G1 X185.727 Y148.974 E81.82596 ; infill
G1 X185.727 Y149.732 E81.87839 ; infill
G1 X150.268 Y114.273 E85.34777 ; infill
G1 X149.510 Y114.273 E85.40020 ; infill
G1 X185.727 Y150.490 E88.94372 ; infill
G1 X185.727 Y151.248 E88.99614 ; infill
G1 X148.752 Y114.273 E92.61381 ; infill
G1 X147.994 Y114.273 E92.66624 ; infill
G1 X185.727 Y152.006 E96.35804 ; infill
G1 X185.727 Y152.763 E96.41047 ; infill
G1 X147.237 Y114.273 E100.17642 ; infill
G1 X146.479 Y114.273 E100.22884 ; infill
G1 X185.727 Y153.521 E104.06894 ; infill
G1 X185.727 Y154.279 E104.12136 ; infill
G1 X145.721 Y114.273 E108.03560 ; infill
G1 X144.963 Y114.273 E108.08802 ; infill
G1 X185.727 Y155.037 E112.07640 ; infill
G1 X185.727 Y155.795 E112.12883 ; infill
G1 X144.205 Y114.273 E116.19135 ; infill
G1 X143.448 Y114.273 E116.24377 ; infill
G1 X185.727 Y156.552 E120.38044 ; infill
G1 X185.727 Y157.310 E120.43286 ; infill
G1 X142.690 Y114.273 E124.64367 ; infill
G1 X141.932 Y114.273 E124.69610 ; infill
G1 X185.727 Y158.068 E128.98104 ; infill
G1 X185.727 Y158.826 E129.03347 ; infill
G1 X141.174 Y114.273 E133.39256 ; infill
G1 X140.417 Y114.273 E133.44499 ; infill
G1 X185.727 Y159.583 E137.87822 ; infill
G1 X185.727 Y160.341 E137.93065 ; infill
G1 X139.659 Y114.273 E142.43802 ; infill
G1 X138.901 Y114.273 E142.49045 ; infill
G1 X185.727 Y161.099 E147.07197 ; infill
G1 X185.727 Y161.857 E147.12439 ; infill
G1 X138.143 Y114.273 E151.78006 ; infill
G1 X137.385 Y114.273 E151.83248 ; infill
G1 X185.727 Y162.615 E156.56229 ; infill
G1 X185.727 Y163.372 E156.61471 ; infill
G1 X136.628 Y114.273 E161.41866 ; infill
G1 X135.870 Y114.273 E161.47109 ; infill
G1 X185.727 Y164.130 E166.34918 ; infill
G1 X185.727 Y164.888 E166.40160 ; infill
G1 X135.112 Y114.273 E171.35383 ; infill
G1 X134.354 Y114.273 E171.40626 ; infill
G1 X185.727 Y165.646 E176.43263 ; infill
G1 X185.727 Y166.404 E176.48506 ; infill
G1 X133.596 Y114.273 E181.58558 ; infill
G1 X132.839 Y114.273 E181.63801 ; infill
G1 X185.727 Y167.161 E186.81267 ; infill
G1 X185.727 Y167.919 E186.86509 ; infill
G1 X132.081 Y114.273 E192.11389 ; infill
G1 X131.323 Y114.273 E192.16632 ; infill
G1 X185.727 Y168.677 E197.48927 ; infill
G1 X185.727 Y169.435 E197.54169 ; infill
G1 X130.565 Y114.273 E202.93878 ; infill
G1 X129.808 Y114.273 E202.99121 ; infill
G1 X185.727 Y170.192 E208.46244 ; infill
G1 X185.727 Y170.950 E208.51487 ; infill
G1 X129.050 Y114.273 E214.06024 ; infill
G1 X128.292 Y114.273 E214.11266 ; infill
G1 X185.727 Y171.708 E219.73218 ; infill
G1 X185.727 Y172.466 E219.78461 ; infill
G1 X127.534 Y114.273 E225.47827 ; infill
G1 X126.776 Y114.273 E225.53069 ; infill
G1 X185.727 Y173.224 E231.29849 ; infill
G1 X185.727 Y173.981 E231.35092 ; infill
G1 X126.019 Y114.273 E237.19286 ; infill
G1 X125.261 Y114.273 E237.24529 ; infill
G1 X185.727 Y174.739 E243.16138 ; infill
G1 X185.727 Y175.497 E243.21380 ; infill
G1 X124.503 Y114.273 E249.20403 ; infill
G1 X123.745 Y114.273 E249.25646 ; infill
G1 X185.727 Y176.255 E255.32083 ; infill
G1 X185.727 Y177.013 E255.37326 ; infill
G1 X122.987 Y114.273 E261.51177 ; infill
G1 X122.230 Y114.273 E261.56420 ; infill
G1 X185.727 Y177.770 E267.77686 ; infill
G1 X185.727 Y178.528 E267.82928 ; infill
G1 X121.472 Y114.273 E274.11608 ; infill
G1 X120.714 Y114.273 E274.16851 ; infill
G1 X185.727 Y179.286 E280.52945 ; infill
G1 X185.727 Y180.044 E280.58188 ; infill
G1 X119.956 Y114.273 E287.01697 ; infill
G1 X119.199 Y114.273 E287.06939 ; infill
G1 X185.727 Y180.801 E293.57862 ; infill
G1 X185.727 Y181.559 E293.63105 ; infill
G1 X118.441 Y114.273 E300.21442 ; infill
G1 X117.683 Y114.273 E300.26684 ; infill
G1 X185.727 Y182.317 E306.92436 ; infill
G1 X185.727 Y183.075 E306.97678 ; infill
G1 X116.925 Y114.273 E313.70844 ; infill
G1 X116.167 Y114.273 E313.76087 ; infill
G1 X185.727 Y183.833 E320.56667 ; infill
G1 X185.727 Y184.590 E320.61909 ; infill
G1 X115.410 Y114.273 E327.49903 ; infill
G1 X114.652 Y114.273 E327.55146 ; infill
G1 X185.727 Y185.348 E334.50554 ; infill
G1 X185.727 Y185.727 E334.53176 ; infill
G1 X185.348 Y185.727 E334.55797 ; infill
G1 X114.273 Y114.652 E341.51205 ; infill
G1 X114.273 Y115.410 E341.56447 ; infill
G1 X184.590 Y185.727 E348.44441 ; infill
G1 X183.833 Y185.727 E348.49684 ; infill
G1 X114.273 Y116.167 E355.30263 ; infill
G1 X114.273 Y116.925 E355.35505 ; infill
G1 X183.075 Y185.727 E362.08670 ; infill
G1 X182.317 Y185.727 E362.13913 ; infill
G1 X114.273 Y117.683 E368.79664 ; infill
G1 X114.273 Y118.441 E368.84906 ; infill
G1 X181.559 Y185.727 E375.43243 ; infill
G1 X180.801 Y185.727 E375.48485 ; infill
G1 X114.273 Y119.199 E381.99407 ; infill
G1 X114.273 Y119.956 E382.04650 ; infill
G1 X180.044 Y185.727 E388.48158 ; infill
G1 X179.286 Y185.727 E388.53401 ; infill
G1 X114.273 Y120.714 E394.89494 ; infill
G1 X114.273 Y121.472 E394.94737 ; infill
G1 X178.528 Y185.727 E401.23416 ; infill
G1 X177.770 Y185.727 E401.28659 ; infill
G1 X114.273 Y122.230 E407.49924 ; infill
G1 X114.273 Y122.988 E407.55166 ; infill
G1 X177.012 Y185.727 E413.69017 ; infill
G1 X176.255 Y185.727 E413.74260 ; infill
G1 X114.273 Y123.745 E419.80696 ; infill
G1 X114.273 Y124.503 E419.85939 ; infill
G1 X175.497 Y185.727 E425.84961 ; infill
G1 X174.739 Y185.727 E425.90204 ; infill
G1 X114.273 Y125.261 E431.81812 ; infill
G1 X114.273 Y126.019 E431.87055 ; infill
G1 X173.981 Y185.727 E437.71248 ; infill
G1 X173.224 Y185.727 E437.76491 ; infill
G1 X114.273 Y126.776 E443.53270 ; infill
G1 X114.273 Y127.534 E443.58513 ; infill
G1 X172.466 Y185.727 E449.27878 ; infill
G1 X171.708 Y185.727 E449.33121 ; infill
G1 X114.273 Y128.292 E454.95072 ; infill
G1 X114.273 Y129.050 E455.00314 ; infill
G1 X170.950 Y185.727 E460.54851 ; infill
G1 X170.192 Y185.727 E460.60094 ; infill
G1 X114.273 Y129.808 E466.07216 ; infill
G1 X114.273 Y130.565 E466.12459 ; infill
G1 X169.435 Y185.727 E471.52167 ; infill
G1 X168.677 Y185.727 E471.57409 ; infill
G1 X114.273 Y131.323 E476.89703 ; infill
G1 X114.273 Y132.081 E476.94946 ; infill
G1 X167.919 Y185.727 E482.19825 ; infill
G1 X167.161 Y185.727 E482.25068 ; infill
G1 X114.273 Y132.839 E487.42533 ; infill
G1 X114.273 Y133.597 E487.47776 ; infill
G1 X166.403 Y185.727 E492.57827 ; infill
G1 X165.646 Y185.727 E492.63070 ; infill
G1 X114.273 Y134.354 E497.65707 ; infill
G1 X114.273 Y135.112 E497.70949 ; infill
G1 X164.888 Y185.727 E502.66172 ; infill
G1 X164.130 Y185.727 E502.71414 ; infill
G1 X114.273 Y135.870 E507.59223 ; infill
G1 X114.273 Y136.628 E507.64465 ; infill
G1 X163.372 Y185.727 E512.44859 ; infill
G1 X162.615 Y185.727 E512.50102 ; infill
G1 X114.273 Y137.385 E517.23082 ; infill
G1 X114.273 Y138.143 E517.28324 ; infill
G1 X161.857 Y185.727 E521.93890 ; infill
G1 X161.099 Y185.727 E521.99132 ; infill
G1 X114.273 Y138.901 E526.57283 ; infill
G1 X114.273 Y139.659 E526.62526 ; infill
G1 X160.341 Y185.727 E531.13263 ; infill
G1 X159.583 Y185.727 E531.18506 ; infill
G1 X114.273 Y140.417 E535.61828 ; infill
G1 X114.273 Y141.174 E535.67071 ; infill
G1 X158.826 Y185.727 E540.02979 ; infill
G1 X158.068 Y185.727 E540.08222 ; infill
G1 X114.273 Y141.932 E544.36716 ; infill
G1 X114.273 Y142.690 E544.41959 ; infill
G1 X157.310 Y185.727 E548.63038 ; infill
G1 X156.552 Y185.727 E548.68281 ; infill
G1 X114.273 Y143.448 E552.81947 ; infill
G1 X114.273 Y144.206 E552.87189 ; infill
G1 X155.794 Y185.727 E556.93441 ; infill
G1 X155.037 Y185.727 E556.98683 ; infill
G1 X114.273 Y144.963 E560.97520 ; infill
G1 X114.273 Y145.721 E561.02763 ; infill
G1 X154.279 Y185.727 E564.94186 ; infill
G1 X153.521 Y185.727 E564.99428 ; infill
G1 X114.273 Y146.479 E568.83437 ; infill
G1 X114.273 Y147.237 E568.88680 ; infill
G1 X152.763 Y185.727 E572.65274 ; infill
G1 X152.006 Y185.727 E572.70516 ; infill
G1 X114.273 Y147.994 E576.39696 ; infill
G1 X114.273 Y148.752 E576.44939 ; infill
G1 X151.248 Y185.727 E580.06705 ; infill
G1 X150.490 Y185.727 E580.11947 ; infill
G1 X114.273 Y149.510 E583.66299 ; infill
G1 X114.273 Y150.268 E583.71541 ; infill
G1 X149.732 Y185.727 E587.18479 ; infill
G1 X148.974 Y185.727 E587.23721 ; infill
G1 X114.273 Y151.026 E590.63244 ; infill
G1 X114.273 Y151.783 E590.68487 ; infill
G1 X148.217 Y185.727 E594.00595 ; infill
G1 X147.459 Y185.727 E594.05838 ; infill
G1 X114.273 Y152.541 E597.30532 ; infill
G1 X114.273 Y153.299 E597.35775 ; infill
G1 X146.701 Y185.727 E600.53055 ; infill
G1 X145.943 Y185.727 E600.58298 ; infill
G1 X114.273 Y154.057 E603.68164 ; infill
G1 X114.273 Y154.815 E603.73406 ; infill
G1 X145.185 Y185.727 E606.75858 ; infill
G1 X144.428 Y185.727 E606.81100 ; infill
G1 X114.273 Y155.572 E609.76138 ; infill
G1 X114.273 Y156.330 E609.81380 ; infill
G1 X143.670 Y185.727 E612.69003 ; infill
G1 X142.912 Y185.727 E612.74246 ; infill
G1 X114.273 Y157.088 E615.54455 ; infill
G1 X114.273 Y157.846 E615.59698 ; infill
G1 X142.154 Y185.727 E618.32492 ; infill
G1 X141.397 Y185.727 E618.37735 ; infill
G1 X114.273 Y158.603 E621.03115 ; infill
G1 X114.273 Y159.361 E621.08358 ; infill
G1 X140.639 Y185.727 E623.66323 ; infill
G1 X139.881 Y185.727 E623.71566 ; infill
G1 X114.273 Y160.119 E626.22118 ; infill
G1 X114.273 Y160.877 E626.27360 ; infill
G1 X139.123 Y185.727 E628.70498 ; infill
G1 X138.365 Y185.727 E628.75741 ; infill
G1 X114.273 Y161.635 E631.11464 ; infill
G1 X114.273 Y162.392 E631.16706 ; infill
G1 X137.608 Y185.727 E633.45015 ; infill
G1 X136.850 Y185.727 E633.50258 ; infill
G1 X114.273 Y163.150 E635.71152 ; infill
G1 X114.273 Y163.908 E635.76395 ; infill
G1 X136.092 Y185.727 E637.89875 ; infill
G1 X135.334 Y185.727 E637.95118 ; infill
G1 X114.273 Y164.666 E640.01184 ; infill
G1 X114.273 Y165.424 E640.06427 ; infill
G1 X134.576 Y185.727 E642.05079 ; infill
G1 X133.819 Y185.727 E642.10321 ; infill
G1 X114.273 Y166.181 E644.01559 ; infill
G1 X114.273 Y166.939 E644.06802 ; infill
G1 X133.061 Y185.727 E645.90625 ; infill
G1 X132.303 Y185.727 E645.95867 ; infill
G1 X114.273 Y167.697 E647.72276 ; infill
G1 X114.273 Y168.455 E647.77519 ; infill
G1 X131.545 Y185.727 E649.46514 ; infill
G1 X130.788 Y185.727 E649.51757 ; infill
G1 X114.273 Y169.212 E651.13337 ; infill
G1 X114.273 Y169.970 E651.18580 ; infill
G1 X130.030 Y185.727 E652.72746 ; infill
G1 X129.272 Y185.727 E652.77989 ; infill
G1 X114.273 Y170.728 E654.24740 ; infill
G1 X114.273 Y171.486 E654.29983 ; infill
G1 X128.514 Y185.727 E655.69321 ; infill
G1 X127.756 Y185.727 E655.74563 ; infill
G1 X114.273 Y172.244 E657.06487 ; infill
G1 X114.273 Y173.001 E657.11730 ; infill
G1 X126.999 Y185.727 E658.36239 ; infill
G1 X126.241 Y185.727 E658.41481 ; infill
G1 X114.273 Y173.759 E659.58576 ; infill
G1 X114.273 Y174.517 E659.63819 ; infill
G1 X125.483 Y185.727 E660.73499 ; infill
G1 X124.725 Y185.727 E660.78742 ; infill
G1 X114.273 Y175.275 E661.81008 ; infill
G1 X114.273 Y176.033 E661.86251 ; infill
G1 X123.967 Y185.727 E662.81103 ; infill
G1 X123.210 Y185.727 E662.86346 ; infill
G1 X114.273 Y176.790 E663.73784 ; infill
G1 X114.273 Y177.548 E663.79026 ; infill
G1 X122.452 Y185.727 E664.59050 ; infill
G1 X121.694 Y185.727 E664.64293 ; infill
G1 X114.273 Y178.306 E665.36902 ; infill
G1 X114.273 Y179.064 E665.42144 ; infill
G1 X120.936 Y185.727 E666.07339 ; infill
G1 X120.178 Y185.727 E666.12582 ; infill
G1 X114.273 Y179.822 E666.70363 ; infill
G1 X114.273 Y180.579 E666.75605 ; infill
G1 X119.421 Y185.727 E667.25972 ; infill
G1 X118.663 Y185.727 E667.31215 ; infill
G1 X114.273 Y181.337 E667.74167 ; infill
G1 X114.273 Y182.095 E667.79409 ; infill
G1 X117.905 Y185.727 E668.14947 ; infill
G1 X117.147 Y185.727 E668.20190 ; infill
G1 X114.273 Y182.853 E668.48314 ; infill
G1 X114.273 Y183.610 E668.53556 ; infill
G1 X116.390 Y185.727 E668.74266 ; infill
G1 X115.632 Y185.727 E668.79508 ; infill
G1 X114.273 Y184.368 E668.92804 ; infill
G1 X114.273 Y185.126 E668.98046 ; infill
G1 X115.115 Y185.968 E669.06285 ; infill
G10 ; retract
G92 E0 ; reset extrusion distance
; Filament-specific end gcode 
;END gcode for filament
M104 S0 ; turn off temperature
M140 S-273
G1 X0 Y300 F1000
M81 S1
; filament used [mm] = 801.0
; filament used [cm3] = 1.9
; total filament used [g] = 0.0
; total filament cost = 0.0
; estimated printing time (normal mode) = 17m 34s

; avoid_crossing_perimeters = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,300x0,300x300,0x300
; bed_temperature = 110
; before_layer_gcode = 
; between_objects_gcode = 
; bottom_fill_pattern = rectilinear
; bottom_solid_layers = 4
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_width = 0
; clip_multipart_objects = 0
; complete_objects = 1
; cooling = 0
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = ""
; default_print_profile = 
; deretract_speed = 0
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; duplicate_distance = 6
; elefant_foot_compensation = 0
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = M104 S0 ; turn off temperature\nM140 S-273\nG1 X0 Y300 F1000\nM81 S1\n
; ensure_vertical_shell_thickness = 0
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extruder_clearance_height = 30
; extruder_clearance_radius = 40
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #80FF00
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 0
; filament_density = 0
; filament_diameter = 1.72
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = ABS
; filament_soluble = 0
; filament_toolchange_delay = 0
; filament_type = ABS
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; fill_angle = 45
; fill_density = 20%
; fill_pattern = rectilinear
; first_layer_acceleration = 0
; first_layer_bed_temperature = 110
; first_layer_extrusion_width = 200%
; first_layer_height = 150%
; first_layer_speed = 50%
; first_layer_temperature = 240
; gap_fill_speed = 20
; gcode_comments = 1
; gcode_flavor = reprap
; gcode_label_objects = 0
; high_current_on_filament_swap = 0
; host_type = duet
; infill_acceleration = 0
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; layer_gcode = 
; layer_height = 0.2
; machine_max_acceleration_e = 10000,5000
; machine_max_acceleration_extruding = 1500,1250
; machine_max_acceleration_retracting = 1500,1250
; machine_max_acceleration_x = 9000,1000
; machine_max_acceleration_y = 9000,1000
; machine_max_acceleration_z = 500,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 500,200
; machine_max_feedrate_y = 500,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 40
; max_layer_height = 0
; max_print_height = 205
; max_print_speed = 100
; max_volumetric_speed = 0
; min_fan_speed = 10
; min_layer_height = 0.07
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; overhangs = 1
; parking_pos_retraction = 92
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 60
; perimeters = 3
; post_process = 
; print_host = 192.168.2.13
; print_settings_id = ABS
; printer_model = 
; printer_notes = 
; printer_settings_id = Hypercube retract
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; printhost_apikey = 
; printhost_cafile = 
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 1
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 60
; seam_position = aligned
; serial_port = 
; serial_speed = 250000
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 3
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 10
; small_perimeter_speed = 15
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 20
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = ;M42 P2 S64   ; LED at 30% PWM on heater 2\n;G32               ; bed levelling\nG28 Z0          ; home all axes\nG29 S1         ; load heightmap\nG1 Z5 F5000 ; lift nozzle\n
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 1
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_spacing = 2
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; temperature = 240
; thin_walls = 1
; threads = 4
; toolchange_gcode = 
; top_fill_pattern = rectilinear
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 15
; top_solid_layers = 4
; travel_speed = 130
; use_firmware_retraction = 1
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0

; Simulated print time: 1055
