; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Thu Jun 11 2020 20:53:46 GMT+0200 (heure d’été d’Europe centrale)

