; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Thu Jun 11 2020 20:53:46 GMT+0200 (heure d’été d’Europe centrale)
; Wait for set temperatures to be reached
M116 P0

